---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor: 
- Karsten Schuldt
title: "Zur Beziehung von Forschung und Öffentlichen Bibliotheken"
pdf: "https://doi.org/10.18452/21539"
doi: "10.18452/21539"
date: 2020-06-24
comments: false
sharing: true
footer: true

---