---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial LIBREAS #37: Forschung und Öffentliche Bibliotheken"
pdf: "master.pdf"
doi: "10.18452/21547"
date: 2020-06-15
comments: false
sharing: true
footer: true

---