---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor: 
- "Sara Juen"
title: "Die Bibliothek als physisches Angriffsziel während sozialer Unruhen"
pdf: "https://doi.org/10.18452/21544"
doi: "10.18452/21544"
date: 2020-06-15
comments: false
sharing: true
footer: true

---