---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor: 
- Mahmoud Hemila
title: "Forschung an öffentlichen Bibliotheken: Chancen und Problemstellungen illustriert am Beispiel von Sprachlernabteilungen"
pdf: "https://doi.org/10.18452/21545"
doi: "10.18452/21545"
date: 2020-06-15
comments: false
sharing: true
footer: true

---