---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor: 
- Sari Herde
title: "Grundsätzlich besser? Finnlands nationale Konzepte, Strategien und Empfehlungen für Bibliotheken"
pdf: "master.pdf"
date: 2020-06-24
comments: false
sharing: true
footer: true

---