---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor: 
- Nathalice Bezerra Cardoso
- Alberto Calil Elias Junior
- Elisa Campos Machado
title: "Der Beitrag der <q>Forschungsgruppe öffentliche Bibliotheken in Brasilien</q> zu Lehre, Forschung und bibliothekswissenschaftlicher Praxis"
abstract: "Dieser Artikel stellt vor, wie die Forschungsgruppe <q>Öffentliche Bibliotheken in Brasilien: Reflexion und Praxis</q> (Grupo de Pesquisa <q>Bibliotecas Públicas no Brasil: reflexão e prática</q>, GPBP), die an der Bundesuniversität des Staates Rio de Janeiro (Universidade Federal do Estado do Rio de Janeiro, UNIRIO) angesiedelt ist, daran arbeitet, den Dialog zwischen der Universität und den öffentlichen Bibliotheken Brasiliens durch Lehre, Forschung und Öffentlichkeitsarbeit zu gewährleisten. Sieben Jahre Forschung haben gezeigt, dass sowohl die Universität als auch die öffentlichen Bibliotheken von einem Wissens- und Erfahrungsaustausch profitieren. Die Universität profitiert, indem sie den Studierenden ermöglicht, die Bibliothekspraxis zu erleben. Die öffentlichen Bibliotheken nutzen die Ergebnisse der Forschung und der Projekte der Gruppe, um konkrete, alltägliche Probleme zu lösen. Es ist zu hoffen, dass dieser Artikel mehr Universitäten dazu motivieren wird, in die Forschung zu und mit öffentlichen Bibliotheken zu investieren."
pdf: "master.pdf"
date: 2020-06-15
comments: false
sharing: true
footer: true

---