---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor: 
- Ulla Wimmer
title: "Wozu Forschen für Öffentliche Bibliotheken?"
pdf: "master.pdf"
date: 2020-06-19
comments: false
sharing: true
footer: true

---