---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor:
- "Rebekka Putzke"
title: "Wünsche an die Forschung – Gedanken aus der Praxis einer Öffentlichen Bibliothek"
pdf: "master.pdf"
doi: "10.18452/21546"
abstract: "Der Beitrag formuliert Anregungen für die Forschung aus der Perspektive der bibliothekarischen Praxis in Öffentlichen Bibliotheken. Er geht auf Möglichkeiten von Forschung aus der Praxis heraus sowie die grundsätzliche Bedeutung wissenschaftlicher Forschung für Öffentliche Bibliotheken und den dafür notwendigen Fachdiskurs ein."
date: 2020-06-08
comments: false
sharing: true
footer: true

---