---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor: 
- Sina Menzel
title: "Gibt es Teaching Librarians an Öffentlichen Bibliotheken? Stellen für die Förderung von Informationskompetenz"
pdf: "master.pdf"
date: 2020-06-19
comments: false
sharing: true
footer: true

---