---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "37"
year: "2020"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #6 (Winter / Frühling 2020)"
pdf: "master.pdf"
date: 2020-06-15
comments: false
sharing: true
footer: true

---